### ISSUE TITLE
Happens sometimes when trying to select mappings or use drawing mode

### ISSUE THREAD

**Issue by Hitaxas** [kirjavascript/Flex2#23]
TypeError: Cannot destructure property 'top' of 'o.init[n]' as it is undefined.
    at file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:487423
    at Array.forEach (<anonymous>)
    at hn.<anonymous> (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:69470)
    at z (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:16:18016)
    at hn.n (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:16:17620)
    at HTMLDivElement.<anonymous> (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:487392)
    at gC.apply (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:453444)
    at g_ (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:442243)
    at Object.a (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:456039)
    at d (file:///C:/Users/Administrator/Documents/GitHub/S2-Full-Throttle/Tools/Flex/resources/app.asar/bundles/main.js:146:454887)

**Comment by kirjavascript** [comment]
Added a workaround in 5df1c15b7b212b97b736e4625e2785829b0b3988 but dont yet know the root cause

Should stop happening in the next release

**Comment by kirjavascript** [comment]
After looking further it seems it happens when you select all or select none or whatever while moving sprite pieces.

Fixed it properly in 8a9a75d6ec0557d4cc941d580fc9f5fe19c6acdd
