### ISSUE TITLE
Out-of-bounds memory access

### ISSUE THREAD

**Issue by flamewing** [kirjavascript/Flex2#25]
```RuntimeError: memory access out of bounds
    at wasm-function[151]:0x8d8a
    at wasm-function[95]:0x6ae3
    at wasm-function[81]:0x664e
    at wasm-function[1017]:0x3f5e9
    at wasm-function[972]:0x39faf
    at Te (file:///<path>/tools/flex/resources/app.asar/bundles/main.js:160:18124)
    at file:///<path>/tools/flex/resources/app.asar/bundles/main.js:160:18750
    at Be (file:///<path>/tools/flex/resources/app.asar/bundles/main.js:160:18773)
    at et.<anonymous> (file:///<path>/tools/flex/resources/app.asar/bundles/main.js:160:31206)
    at we (file:///<path>/tools/flex/resources/app.asar/bundles/main.js:15:6740)
```
`<path>` was redacted for simplicity. Got this error with these settings:

![image](https://user-images.githubusercontent.com/6319024/93027229-dfeac680-f60b-11ea-80e5-945db1065f73.png)

On an otherwise empty project. Using Windows x64 version, on Windows 10 v2004.

**Comment by flamewing** [comment]
Manually decompressing the art file seems to have worked.

**Comment by kirjavascript** [comment]
can't seem to reproduce this on linux

![](https://i.imgur.com/c7mtfxv.png)

I assume the bug is consistent. The art file is rather small so I can't imagine it's an issue with memory. 

will have to get a win10 VM setup
