### ISSUE TITLE
Error Report for Flex 2 0.0.8

### ISSUE THREAD

**Issue by ThunderStorm-Technologies** [kirjavascript/Flex2#29]
You can move the selected mappings in any direction, but if you try to move the selected mappings up or down by more than one pixel by typing in the multiplier then pressing the arrow key, the following error occurs:
# Unhandled Error
TypeError: Cannot read property 'preventDefault' of undefined
    at Object.func (file:///resources/app.asar/bundles/main.js:160:375730)
    at file:///resources/app.asar/bundles/main.js:160:389219
    at et.<anonymous> (file:///resources/app.asar/bundles/main.js:160:33458)
    at we (file:///resources/app.asar/bundles/main.js:15:6740)
    at et.r (file:///resources/app.asar/bundles/main.js:15:6636)
    at Ix (file:///resources/app.asar/bundles/main.js:160:389157)
    at u (file:///resources/app.asar/bundles/main.js:20:4141)
    at y.t._handleKey (file:///resources/app.asar/bundles/main.js:20:5384)
    at y.handleKey (file:///resources/app.asar/bundles/main.js:20:2280)
    at HTMLDocument.h (file:///resources/app.asar/bundles/main.js:20:4392)

Trying to report the error would give you another error:
# Unhandled Promise Rejection
Error: Failed to open

**Comment by kirjavascript** [comment]
thanks for the bug report!

I've confirmed the bug and it'll be fixed in the next version
