### ISSUE TITLE
This happens when I attempt to close a project.

### ISSUE THREAD

**Issue by guy42** [kirjavascript/Flex2#32]
TypeError: this.project.cleanup is not a function
    at file:///C:/flex2/resources/app.asar/bundles/main.js:192:105519
    at we (file:///C:/flex2/resources/app.asar/bundles/main.js:15:6740)
    at r (file:///C:/flex2/resources/app.asar/bundles/main.js:15:6636)
    at Object.l (file:///C:/flex2/resources/app.asar/bundles/main.js:135:456)
    at p (file:///C:/flex2/resources/app.asar/bundles/main.js:135:599)
    at file:///C:/flex2/resources/app.asar/bundles/main.js:135:745
    at m (file:///C:/flex2/resources/app.asar/bundles/main.js:135:831)
    at at (file:///C:/flex2/resources/app.asar/bundles/main.js:135:16359)
    at ot (file:///C:/flex2/resources/app.asar/bundles/main.js:135:16169)
    at lt (file:///C:/flex2/resources/app.asar/bundles/main.js:135:16525)

**Comment by kirjavascript** [comment]
fixed in 1.1.1

alternatively you can press `f12` and then type `log` in the debugger to get a debug menu that allows you to 'clear storage' and open a fixed project
